### PR TITLE
Added SIGTERM handler for graceful termination

### PR DESCRIPTION
**Pull request by fj604**
Added SIGTERM handler for graceful service shutdown, equivalent to SIGINT

**Clearly describe the problem and solution**
SIGTERM handler ensures that all queues are drained before the service is shut down, reducing chances of data loss caused by shutdown or restart.

**Relevant issue number(s) if applicable**
N/A

**Did you run `npm run lint` from the viewer or parliament directory (whichever you are making changes to) and correct any errors**
N/A - no changes to viewer

**Did you Ensure that all tests still pass by navigating to the `tests` directory and running `./tests.pl --viewer`**
N/A - no changes to viewer

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by awick** [comment]
Why is TERM need since its the same as INT?

**Comment by fj604** [comment]
> Why is TERM need since its the same as INT?

When the server (physical or virtual) is shut down or rebooted, molochcapture.service receives SIGTERM and not SIGINT.

**Comment by awick** [comment]
ok, please update to call exit on second call like controlc does

**Comment by fj604** [comment]
> ok, please update to call exit on second call like controlc does

When the service is stopped (manually or upon shutdown or reboot), for some reason SIGTERM is sent twice. If I add the same update as in controlc then the second SIGTERM would cause immediate exit which is what I'm trying to prevent.

**Comment by awick** [comment]
i think you need to figure out why that happens

**Comment by fj604** [comment]
> i think you need to figure out why that happens

This has something to do with moloch-capture stopped by systemd.  If I kill the service with the `kill` command, I see only one `SIGTERM` sent, but `systemctl stop molochcapture.service` sends `SIGTERM` twice.

**Comment by fj604** [comment]
Yes, definitely something to do with systemd.
If moloch-capture is started with `service molochcapture start` then either ` systemctl stop molochcapture.service` or `service molochcapture stop` sends one SIGTERM.
If moloch-capture is started with `systemctl atart molochcapture.service` then either `service molochcapture stop` or `systemctl stop molochcapture.service` sends SIGTERM twice.

**Pull request merged**
