### PR TITLE
Update Configure and moloch/release/README.txt

### PR DESCRIPTION
**Pull request by Wapiti08**
**Clearly describe the problem and solution**

**Relevant issue number(s) if applicable**

**Did you run `npm run lint` from the viewer or parliament directory (whichever you are making changes to) and correct any errors**

**Did you Ensure that all tests still pass by navigating to the `tests` directory and running `./tests.pl --viewer`**

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by awick** [comment]
* I fixed the es download url code, thanks for pointing that out
* Looks like you updated the README for running out of the git directory, that isn't what we recommend nor will it work with the packages.

**Comment by Wapiti08** [comment]
For the README, I found it is for the package download. You are right. No need to modify. But when I download it from the git, the instructions on **install** it is not that clear. Cuz it uses the README in the release folder. Hope you can split it or specify this part. Thanks.

**Comment by awick** [comment]
The README in the release directory is for releases.

The CONTRIBUTING.md is probably the closest thing we have for folks wanting to run out of the git directory.

**Comment by Wapiti08** [comment]
Cool. I got that. Thanks.

**Pull request closed without merging**
