### PR TITLE
show es errors instead of "Oh no, moloch is empty..."

### PR DESCRIPTION
**Pull request by jakup**
**Steps to reproduce:** attempt to sort on a field that doesn't have a mapping.  viewer log shows an exception from elasticsearch.  moloch ui shows "Oh no, moloch is empty".

> ERROR - /sessions.json error { Error: [query_shard_exception] No mapping found for [tls.ja3] in order to sort on, with { index_uuid="vXob9QDiSHOumz4Df5p6Fg" & index="sessions2-180718" }
>     at respond (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:307:15)
>     at checkRespForFailure (/data/moloch/node_modules/elasticsearch/src/lib/transport.js:266:7)
>     at HttpConnector.<anonymous> (/data/moloch/node_modules/elasticsearch/src/lib/connectors/http.js:159:7)
>     at IncomingMessage.bound (/data/moloch/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
>     at emitNone (events.js:111:20)
>     at IncomingMessage.emit (events.js:208:7)
>     at endReadableNT (_stream_readable.js:1064:12)
>     at _combinedTickCallback (internal/process/next_tick.js:138:11)
>     at process._tickCallback (internal/process/next_tick.js:180:9)
>   status: 400,
>   displayName: 'BadRequest',
>   message: '[query_shard_exception] No mapping found for [tls.ja3] in order to sort on, with { index_uuid="vXob9QDiSHOumz4Df5p6Fg" & index="sessions2-180718" }',
>   path: '/sessions2-180718/session/_search',
>   query: {},
>   body:
>    { error:
>       { root_cause: [Array],
>         type: 'search_phase_execution_exception',
>         reason: 'all shards failed',
>         phase: 'query',
>         grouped: true,
>         failed_shards: [Array] },
>      status: 400 },
>   statusCode: 400,
>   response: '{"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [tls.ja3] in order to sort on","index_uuid":"vXob9QDiSHOumz4Df5p6Fg","index":"sessions2-180718"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"sessions2-180718","node":"aG_W93OYRku89-AwiGNhvA","reason":{"type":"query_shard_exception","reason":"No mapping found for [tls.ja3] in order to sort on","index_uuid":"vXob9QDiSHOumz4Df5p6Fg","index":"sessions2-180718"}}]},"status":400}',
>   toString: [Function],
>   toJSON: [Function] }

### CODE REVIEW

**Comment by awick** [comment]
Trying to get away from showing stack traces in the UI.  Maybe just a msg that says something happen, go check viewer.log? @31453 what do you think.

**Comment by jakup** [comment]
The error displayed in the UI is:
> Elasticsearch error: [query_shard_exception] No mapping found for [tls.ja3] in order to sort on, with { index_uuid="vXob9QDiSHOumz4Df5p6Fg" & index="sessions2-180718" }

It shouldn't be the entire stack trace unless you return the Error object.  Perhaps we can make this a configurable option?  It's very helpful to provide the operators feedback indicating the query failed instead of 'no results' or 'moloch is empty'.

**Comment by awick** [comment]
I agree we should tell them there was a problem.  Just wondering if we should show them a ES error or a more generic "There was an Elasticsearch issue, tell your Moloch admin to look at viewer.log for more information"

**Comment by 31453** [comment]
I agree, a better error is necessary in this case, I'm just not sure what the best error is. A normal user will most likely not understand the ES error, however it is better than the empty Moloch error.

**Comment by sfd** [comment]
The short form of the ES error seems reasonable. It at least gives people something to google (without having to read through log files)?

**Pull request closed without merging**
