### PR TITLE
allow reading of truncated packets for live captures

### PR DESCRIPTION
**Pull request by winstonliu1111**
Hi, I noticed that this fix was there for the offline capture case, but not for the live capture case, which was causing the program to exit whenever there is a truncated packet even when all the hw offload features are turned off.

### CODE REVIEW

**Comment by awick** [comment]
I don't really want to add this.  Are you running in a VM?  did you turn off everything on the physical interface too?

**Comment by winstonliu1111** [comment]
i'm running this within a docker container, where I have no access to the underlying docker host/infrastructure.

it's not turned on by default, it's an option, the default behavior is still the same as previously.

**Comment by awick** [comment]
Yes, but people will find the option, and turn it on instead of fixing their deployment and then complain when it doesn't work right.  With truncated packets moloch will not be able to decode things correctly.

**Comment by winstonliu1111** [comment]
yeah, i see your point about how people will turn it on without realizing the consequences and complain.  I was under the assumption that people understands the potential that certain sessions/flows will not be decoded correctly where truncated packets occur.  for someone who has no control over the underlying infrastructure (this can be VM on top of a physical machine in public cloud environments), this seemed like an acceptable tradeoff.  are most of the deployments/users today have access to their underlying infrastructure?  I'm just wondering if I'm the snowflake?

**Pull request closed without merging**
