### PR TITLE
Use enum instead of #define

### LINKED ISSUE #1380: #define ⇒ enum?
Would you like to replace [more defines for constant values](https://github.com/aol/moloch/blob/664ffe25810380f12823941c210efad4e9881124/capture/moloch.h#L158 "MOLOCH_FIELD_TYPE_…") by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages "Description for the usage of enumerations") to stress their relationships?

### PR DESCRIPTION
**Pull request by komainu8**
Hello,

I fixed #1380 within the limits of my ability.

# License

I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by awick** [comment]
Everyplace that uses the enums needs to change from int to the new types that have been defined

**Comment by komainu8** [comment]
Thank you for your comment.
You're right. I'll also modify them.

**Comment by awick** [comment]
This is getting closer, thanks for working on it
1) can you remove the s at the name of the two types.  So MolochFieldType and MolochSessionType
2) There are several switch statements with errors now, mainly about missing MOLOCH_FIELD_TYPE_CERTSINFO you think you can fix those or want me to?

**Comment by komainu8** [comment]
> 1. can you remove the s at the name of the two types. So MolochFieldType and MolochSessionType

I understand. I'm fixing them.

> 2. There are several switch statements with errors now, mainly about missing MOLOCH_FIELD_TYPE_CERTSINFO you think you can fix those or want me to?

Thank you for your comment.
I want to ask the revision of you. Because I don't understand this problem details.

**Pull request merged**
