### PR TITLE
Sticky table header

### LINKED ISSUE #1416: Feature Request: fix table header
allow a user to fix the table header on the sessions page and scroll the body of the table

### PR DESCRIPTION
**Pull request by 31453**
Make the sessions table header stick to the top of the page with the sticky visualization. The table is scrollable but the header will always stay at the top in the same position.

One caveat: a user cannot scroll the headers left/right. So if the table is wider than the window, and they scroll right, the table body cells no longer match the header columns.

Fixes #1416

### CODE REVIEW

**Comment by BryceV** [comment]
Interesting! I see what you are doing here. A couple things I noticed:
- If you open a menu in the sticky state, then deselect sticky, the dropdown for the table headers will be squashed. 
- The headers act strangely in sticky mode when there are only a few columns (try 1 to 3). This is close to what you were saying about the caveat about the table stretching horizontally. 
- "Fit the window to the current table size" button is part of the vertical scroll on the thead > tr when sticky is on. It gets pushed far down and is hidden. 
- In sticky mode the overflow-x: scroll adds a border under the table header. Its a design choice but maybe overflow-x: auto works better if we want to remove that border.

**Comment by 31453** [comment]
- How do I reproduce this one? I'm clicking on a dropdown while in sticky mode, then unselecting sticky mode, then opening a dropdown again. I don't see any changes to the dropdown or the table headers. Which dropdown are you clicking? What are your exact steps to reproduce?
- This is a strange one! I think I might need to re-render the entire table when toggling sticky mode 😕 
- Nice find! 👍 
- Auto doesn't provide the same behavior in letting the dropdowns overflow the column header row container unfortunately, so scroll is required. I'm not seeing the bottom border. There is however a drop shadow to try to indicate that the header is stuck to the top.

**Comment by 31453** [comment]
Never mind on the first bullet point! I was able to reproduce it (I was closing the dropdown before clicking the unstick button).

**Comment by BryceV** [comment]
Nice! I still see the fit button scrolling with the page and it crosses over the collapsable section. Also, the 310px top is not going to respond to the collapsing action. 

It looks like you did something with the thead bottom border. There is a shadow but also a border on chrome when its in sticky mode and  after a dropdown toggle. I think its added from the overflow-x.

**Comment by 31453** [comment]
I already forgot about that new feature 🤦 Thanks for the reminder!

**Pull request merged**
