### PR TITLE
Enable batch build in scripts

### PR DESCRIPTION
**Pull request by kost**
The code still supports old interactive mode of scripts, but also this patch enables that moloch can be built automatically, something like:

USEPFRING=no ESMEM="512M" DONOTSTART=yes USERNAME=daemon GROUPNAME=daemon PASSWORD=0mgMolochRules1 INTERFACE=eth0 BATCHRUN=yes ./easybutton-singlehost.sh

Something like this helps in automatically building lxc/docker/vm images.

### CODE REVIEW

**Comment by awick** [comment]
USERNAME is probably bad since thats set in linux.

A more meta question is why not just build it with your own scripts, the easy button stuff isn't required.

**Comment by kost** [comment]
USERNAME is already used in the original script, but I can change that. 

Regarding meta question: i don't wanna build my own tree and scripts - would be good to stay as close as possible with original. I need that for docker image I've built (as I didn't see any):
https://github.com/kost/docker-moloch/

And currently I'm using my own branch:
https://github.com/kost/docker-moloch/blob/master/scripts/buildmoloch.sh

Would like to use original repository/branch (aol/moloch).

**Comment by kost** [comment]
Renamed USERNAME to MOLOCHUSER in additional commit/push. So, I guess it is ready to go ;)

**Comment by awick** [comment]
Not sure this is really the direction to go, but folks seem to want it.  Wasn't asking you to maintain a branch but all this script does is build it using normal configure and make sure dependancies are installed.  Must be a better way ...

**Pull request merged**
