### PR TITLE
Fix for #1377

### PR DESCRIPTION
**Pull request by mammo0**
Please have a look at #1377.

I described my problem there in detail (also see my comments in this issue) and what solutions I found. If you have additional questions, just ask them.
Thank you.

### CODE REVIEW

**Comment by awick** [comment]
Its not clear to me any of these changes are needed after the updates we've made.
What scroll timeout are you using?  Any reason to just not use that everywhere?

**Comment by awick** [comment]
* Ah I missed the "get the size of the query if it is being restarted" change, that should be removed
* I'm not sure another setting for esScrollTimeout is useful, if you have a better number lets just use it
* the remote query stuff shouldn't use the esQueryTimeout since its not a es query.  We currently have it set to 20 minutes, which seems like it should be enough.

**Comment by mammo0** [comment]
## 1)
> Ah I missed the "get the size of the query if it is being restarted" change, that should be removed

I removed these lines of code, because of the `Batch size is too large, size must be less than or equal
to: [10000]` error message. If this calculation is necessary, can you please explain me why?


## 2)
> I'm not sure another setting for esScrollTimeout is useful, if you have a better number lets just use it

In my current setup I set this to 1800s. But this value was needed because I performed a Hunt search through around 10TB of network data. This job took about 1,5 weeks... I don't think that this high value should be used as a default.
The ES docu says about a high value (https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#scroll-search-context):
> Keeping older segments alive means that more disk space and file handles are needed. Ensure that you have configured your nodes to have ample free file handles. See File Descriptors.

So I think a configurable parameter would make sense here...


## 3)
> the remote query stuff shouldn't use the esQueryTimeout since its not a es query. We currently have it set to 20 minutes, which seems like it should be enough.

I ran into this issue because I use Docker to run the Moloch viewer. Every time I created a new container (e.g. after an update) the hostname of the container changed to a random value.
Because of that the current viewer instance thought that a previously added Hunt job was added by a remote viewer and therefore performed the remote requests. And for those remote requests the timeout was I think only 60s.

In my case I fixed this issue by adding `--host localhost` parameter when launching the viewer. This overrides the random hostname of the Docker container. And now the viewer performs local queries, not remote ones.

I saw that you increased this timeout to a hard coded value of 20min. But as you see in 2) I'm not a fan of hard coded values ;)
So I used the `esQueryTimeout` value here. Does this remote call not initiate a query on the remote viewer? If so, why do not use the same timeout as for a local query here? Maybe a some extra time should be added to avoid latency problems.

Please let me know, what you think.

**Comment by awick** [comment]
>

> ## 1)
> > Ah I missed the "get the size of the query if it is being restarted" change, that should be removed
> 
> I removed these lines of code, because of the `Batch size is too large, size must be less than or equal to: [10000]` error message. If this calculation is necessary, can you please explain me why?

Yes, I was agreeing with you that this part of the PR is needed, sorry it wasn't clear.

> 
> ## 2)
> > I'm not sure another setting for esScrollTimeout is useful, if you have a better number lets just use it
> 
> In my current setup I set this to 1800s. But this value was needed because I performed a Hunt search through around 10TB of network data. This job took about 1,5 weeks... I don't think that this high value should be used as a default.
> The ES docu says about a high value (https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#scroll-search-context):
> 
> > Keeping older segments alive means that more disk space and file handles are needed. Ensure that you have configured your nodes to have ample free file handles. See File Descriptors.
> 
> So I think a configurable parameter would make sense here...

What would it hurt setting to 1800s everywhere?  Just need to make sure we do a clearScroll.  What this value should be is just how long it takes to search 100 sessions.


> 
> ## 3)
> > the remote query stuff shouldn't use the esQueryTimeout since its not a es query. We currently have it set to 20 minutes, which seems like it should be enough.

> I saw that you increased this timeout to a hard coded value of 20min. But as you see in 2) I'm not a fan of hard coded values ;)

I'm not a fan just adding a million new config vars, plus defaults should be sane.  
It shouldn't be the same as esQueryTimeout because what is taking the majority of the time is the searching of the pcap, not going against ES.  Also I noticed there is a 10minute timeout on the receiving side that needs to be updated anyway.

**Comment by mammo0** [comment]
> Yes, I was agreeing with you that this part of the PR is needed, sorry it wasn't clear.

Ok, misunderstood this point.

> What would it hurt setting to 1800s everywhere? Just need to make sure we do a clearScroll. What this value should be is just how long it takes to search 100 sessions.

How you mean. I didn't test a lower value in my setup. I just set this value and it worked. Maybe the point is, that I had a lot of sessions with the maximum packet size of 10.000. Maybe a value of 20min (1200s) works as well... So this would be consistent to the other 20min timeouts...

> I'm not a fan just adding a million new config vars, plus defaults should be sane.

Hehe :)
It's your software, so you decide ;) I just can make suggestions.

> It shouldn't be the same as esQueryTimeout because what is taking the majority of the time is the searching of the pcap, not going against ES. Also I noticed there is a 10minute timeout on the receiving side that needs to be updated anyway.

I'm not as deep as you in the whole Moloch source code. So I think you know more what you do than me.

**Comment by awick** [comment]
Thanks, I merged the first 2 parts

**Pull request closed without merging**
