### PR TITLE
Allow more control over the logging in viewer

### PR DESCRIPTION
**Pull request by pjsg**
**Clearly describe the problem and solution**

This adds two more configuration items to control the request logging in the viewer. In particular it allows the log format to be chosen (e.g. without any escape sequences) and whether the eshealth.json should be logged as well.

**Relevant issue number(s) if applicable**

#1375 

**Did you run `npm run lint` from the viewer or parliament directory (whichever you are making changes to) and correct any errors**

Yes

**Did you Ensure that all tests still pass by navigating to the `tests` directory and running `./tests.pl --viewer`**

Yes

## License
I confirm that this contribution is made under an Apache 2.0 license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by awick** [comment]
haha You already had a PR, i'll start waiting on your issues :). Thoughts about allowing an array instead of just that one url?

**Comment by pjsg** [comment]
I'm going to update to include the array.

**Comment by pjsg** [comment]
This now uses the array for a list of paths.

**Comment by awick** [comment]
Thanks! Please update the settings.html page when you get a chance.

**Pull request merged**
